### ISSUE TITLE
Setup a test environment for ubo app so that we can have end to end tests

### ISSUE THREAD

**Issue by sassanh** [ubopod/ubo-app#44]
As the system is growing and there are multiple modules working together, we need end to end tests to make sure all features are working before delivering new features.
To implement these end-to-end tests we need to research existing options for testing software running on RPi. For example to see if pressing a key on ubo-pod results in dispatching particular actions in the ubo-app which then causes some side effects on the LEDs or the display, etc we need to be able to emulate signals of different ports of the RPi.
Once we have an emulator, we should be able to write effective end to end tests.

**Comment by mehrdadfeller** [comment]
you could potentially emulate keypad presses by sending keyboard events. That will bypass actual keypad function and won't test that though. I guess here we can assume the hardware attraction layer is tested separately (such as by factory testing process). It would be great to add hardware test flow in the GUI so that if there is a doubt about hardware issues, users can run that test. BTW, in the video below I demonstrate the factory testing process:

https://www.youtube.com/watch?v=X0lBcDt_kOM
