### ISSUE TITLE
SSH stops listening on port 22 after restart

### ISSUE THREAD

**Issue by mehrdadfeller** [ubopod/ubo-app#55]
Even if I create a new permanent user after logging in with the `_tmp_x` user, I cannot SSH to the device after a restart. I have to go back to the SSH menu to create a new user for the SSH to start listening on port 22 again. This behavior is undesirable since it can force the user take extra steps to re-enable SSH. Perhaps this can be changed by a settings parameter or just start SSH server at restart by default.  

How to reproduce:
1.  SSH and add a new user
2. Restart
3. Attempt to connect via SSH

**Comment by sassanh** [comment]
@mehrdadfeller I think this is the default behavior if you don't enable ssh in the Pi Imager here:
<img width="534" alt="image" src="https://github.com/ubopod/ubo-app/assets/1270688/bbe7f3fe-ef4e-44d3-bdfa-b1fa3fdc62f5">
I guess the ssh service is not up even in the first boot, but whenever you create a new temporary account, it restarts the ssh service (causing it to start if it is stopped). But it just starts it for the current session, after you reboot it won't start again because it is not enabled.
Do you think we should enable the ssh service manually?
